# Generated by Django 4.1.7 on 2023-03-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formapago',
            fields=[
                ('idformapago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tipopizza',
            fields=[
                ('idtipopizza', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('contrasena', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=70)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formapago', models.ForeignKey(db_column='idformapago', on_delete=django.db.models.deletion.CASCADE, related_name='fk_formapago', to='inicioApp.formapago')),
                ('tipopizza', models.ForeignKey(db_column='idtipopizza', on_delete=django.db.models.deletion.CASCADE, related_name='fk_tipopizza', to='inicioApp.tipopizza')),
            ],
        ),
    ]
